### ISSUE TITLE
Issue with doubled arguments with simple fix

### ISSUE THREAD

**Issue by purevg** [FuriLabs/flatpak-hybris#2]
https://github.com/FuriLabs/flatpak-hybris/blob/6c66f587011b286368b4ea4b75d8aee91b1d17c7/src/bwrapwrapper.sh#L32

We can see with a simple test that the arguments are doubled if --args is not used:

Test with:

`bwrap --ro-bind / / --proc /proc --unshare-all echo test
`
results in

`test --ro-bind / / --proc /proc --unshare-all echo test
`
Instead of

`test
`
To fix, this simple patch (removing "$@" from the last line) works:

```
--- /root/bwrap.origin  2025-08-30 17:22:02.720761141 +0200
+++ /usr/bin/bwrap      2025-08-30 19:41:36.779004388 +0200
@@ -28,5 +28,5 @@
     esac
 done
 
-args=("${args[@]}")
-exec "$BWRAP" "${args[@]}" "$@"
+#args=("${args[@]}")
+exec "$BWRAP" "${args[@]}"
```

I also commented the line 31 as I don't understand why it would be necessary.

**Comment by purevg** [comment]
This fix is not working when using --args it misses the "$@" from the args, so it needs to be added back but before processing the search for "--unshare-all". This version of the patch is a better fix:

```
--- /root/bwrap.origin  2025-08-30 17:22:02.720761141 +0200
+++ /usr/bin/bwrap      2025-09-08 13:26:13.653201793 +0200
@@ -13,6 +13,7 @@
     fd=$1
     shift 1
     readarray -d '' args < /dev/fd/$fd
+    args+=("$@")
 else
     args=("$@")
 fi
@@ -28,5 +29,5 @@
     esac
 done
 
-args=("${args[@]}")
-exec "$BWRAP" "${args[@]}" "$@"
+#args=("${args[@]}")
+exec "$BWRAP" "${args[@]}"
```

**Comment by FakeShell** [comment]
I am testing this with the latest version now and using echo to print the arguments like so: `echo "$BWRAP" "${args[@]}" "$@"`
executing your test gives me:
```
furios@FuriPhoneFLX1s:~/flatpak-hybris$ bwrap --ro-bind / / --proc /proc --unshare-all echo test 
/usr/bin/bwrap.real --ro-bind / / --proc /proc echo test
test
```

and it seems to work fine. i think maybe this issue was resolved in the past couple months.
closing as solved, but if you find any other reproducer for this, feel free to reopen.

**Comment by purevg** [comment]
Hello, for my simple test, the new version seems to be better and works. I think this is thanks to the presence of  "set --" which resets argument list after having them added to the "args" array.

But according to the manual, the wrapper is still broken. For example, the script only check if "--args" is present in the first argument, but the manual explicitly says it can be specified multiple times: "This option can be used multiple times to parse options from multiple sources.".
